services:
  # PostgreSQL DB
  postgres:
    image: postgres
    container_name: snowflake-postgres
    environment:
      POSTGRES_USER: snowflake
      POSTGRES_PASSWORD: snowflake
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - microservices-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'snowflake']
      interval: 1s
      timeout: 1s
      retries: 3

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: snowflake-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: snowflake
      RABBITMQ_DEFAULT_PASS: snowflake
    volumes:
      - ./init/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservices-network
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 1s
      timeout: 1s
      retries: 3

  # Proxy Server
  nginx:
    image: nginx:latest
    container_name: snowflake-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservices-network
    depends_on:
      - authentication
      - scorer
      - loan

  # Authentication Service
  authentication:
    build:
      context: ./helium
    image: snowflake-authentication
    container_name: snowflake-authentication
    ports:
      # Exposing gRPC for now because nginx refuses to work
      - '50050:50050'
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - microservices-network

  # Scorer Service
  scorer:
    build:
      context: ./carbon
    image: snowflake-scorer
    container_name: snowflake-scorer
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      authentication:
        condition: service_started
    networks:
      - microservices-network

  # Loan Service
  loan:
    build:
      context: ./oxygen
    image: snowflake-loan
    container_name: snowflake-loan
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      authentication:
        condition: service_started
      scorer:
        condition: service_started
    networks:
      - microservices-network

# Network Configuration
networks:
  microservices-network:
    driver: bridge
